[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x3567f7aabd0c861217a1752002b2df358c49dcc5fc4ee2a1b63ce2834d326298'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]